# Setup
title:            'State of Connecticut'
tagline:          'Data Sharing Playbook'
description:      'Connecticut Data Playbook'

author:
  name:           'State of Connecticut'
  url:            https://github.com/CTOpenData/data-sharing-playbook

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/CTOpenData/data-sharing-playbook

# Google Analytics
google_analytics: UA-56144207-2
